music.setVolume(53)
music.playTone(277, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(294, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(247, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(500)
music.playTone(277, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(294, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(247, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(494, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(415, music.beat(BeatFraction.Whole))
